version: "3"

services:
  vivienda-api-test:
    build: .
    restart: unless-stopped
    container_name: vivienda-test
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 80"
    volumes:
      - .:/app
    ports:
      - 5191:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db:
    restart: unless-stopped
    image: postgres:13-alpine
    volumes:
      - vivienda_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=Anakin
      - POSTGRES_PASSWORD=Anakin4
      - POSTGRES_DB=vivienda
volumes:
  vivienda_data:
