"""adding is locked status to phase

Revision ID: 139b71362001
Revises: 69b9d56c4535
Create Date: 2021-12-03 16:53:29.354881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '139b71362001'
down_revision = '69b9d56c4535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_phase', sa.Column('is_locked', sa.Boolean(), server_default='0', nullable=False))
    op.create_unique_constraint(None, 'employee_phase', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee_phase', type_='unique')
    op.drop_column('employee_phase', 'is_locked')
    # ### end Alembic commands ###
