"""adding diagnostic table

Revision ID: 6395ce8c85e6
Revises: 83cdbc89f1b7
Create Date: 2021-12-03 14:37:17.678503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6395ce8c85e6'
down_revision = '83cdbc89f1b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_diagnostic',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rsh', sa.String(length=120), nullable=True),
    sa.Column('rsh_id', sa.Integer(), nullable=False),
    sa.Column('commune', sa.String(length=120), nullable=True),
    sa.Column('commune_id', sa.Integer(), nullable=False),
    sa.Column('current_subsidy', sa.String(length=150), nullable=False),
    sa.Column('target_subsidy', sa.String(length=150), nullable=False),
    sa.Column('atc', sa.String(length=2), nullable=False),
    sa.Column('disability', sa.String(length=2), nullable=False),
    sa.Column('marital_status_id', sa.Integer(), nullable=False),
    sa.Column('salary', sa.Float(), nullable=False),
    sa.Column('contract_type', sa.String(length=50), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'employee_saving', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee_saving', type_='unique')
    op.drop_table('employee_diagnostic')
    # ### end Alembic commands ###
