"""adding employee saving

Revision ID: 83cdbc89f1b7
Revises: 6cc0cab2e496
Create Date: 2021-12-03 07:05:36.116297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83cdbc89f1b7'
down_revision = '6cc0cab2e496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_saving',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity', sa.String(length=30), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'agreement', ['id'])
    op.create_unique_constraint(None, 'employee', ['id'])
    op.create_unique_constraint(None, 'professional', ['id'])
    op.create_unique_constraint(None, 'related_business', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'related_business', type_='unique')
    op.drop_constraint(None, 'professional', type_='unique')
    op.drop_constraint(None, 'employee', type_='unique')
    op.drop_constraint(None, 'agreement', type_='unique')
    op.drop_table('employee_saving')
    # ### end Alembic commands ###
